image:
  repository: your-registry/health-hapi-fhir
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

env: []
# Exemplo:
# env:
#   - name: SPRING_DATASOURCE_URL
#     value: jdbc:postgresql://postgres:5432/fhir

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

config:
  enabled: false
  data: {}
  # Exemplo:
  # data:
  #   hapi.properties: |
  #     hapi.fhir.default_encoding=json
  #     hapi.fhir.allow_external_references=true
